export const MOCK_CITIES = [
  {
    id: "city-paris",
    name: "Paris",
    country: "France",
    state: null,
    description: "The City of Light - known for its art, fashion, gastronomy, and culture.",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: "Europe/Paris",
    currency: "EUR",
    language: "French",
    popularity: 95,
    costIndex: 130,
    _count: { activities: 5 },
  },
  {
    id: "city-tokyo",
    name: "Tokyo",
    country: "Japan",
    state: null,
    description: "A dazzling mix of ultra-modern and traditional, from neon-lit skyscrapers to historic temples.",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: "Asia/Tokyo",
    currency: "JPY",
    language: "Japanese",
    popularity: 92,
    costIndex: 145,
    _count: { activities: 5 },
  },
  {
    id: "city-nyc",
    name: "New York City",
    country: "USA",
    state: "NY",
    description: "The city that never sleeps - a global hub of culture, finance, and entertainment.",
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800",
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    currency: "USD",
    language: "English",
    popularity: 98,
    costIndex: 160,
    _count: { activities: 5 },
  },
  {
    id: "city-rome",
    name: "Rome",
    country: "Italy",
    state: null,
    description: "The Eternal City - ancient history meets la dolce vita.",
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800",
    latitude: 41.9028,
    longitude: 12.4964,
    timezone: "Europe/Rome",
    currency: "EUR",
    language: "Italian",
    popularity: 90,
    costIndex: 115,
    _count: { activities: 4 },
  },
  {
    id: "city-bali",
    name: "Bali",
    country: "Indonesia",
    state: null,
    description: "Tropical paradise with stunning beaches, rice terraces, and rich culture.",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800",
    latitude: -8.4095,
    longitude: 115.1889,
    timezone: "Asia/Makassar",
    currency: "IDR",
    language: "Indonesian",
    popularity: 88,
    costIndex: 55,
    _count: { activities: 4 },
  },
  {
    id: "city-london",
    name: "London",
    country: "UK",
    state: null,
    description: "Historic royal city with world-class museums, theater, and culture.",
    imageUrl: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800",
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: "Europe/London",
    currency: "GBP",
    language: "English",
    popularity: 94,
    costIndex: 155,
    _count: { activities: 4 },
  },
  {
    id: "city-barcelona",
    name: "Barcelona",
    country: "Spain",
    state: null,
    description: "Gaudí's architectural wonders meet Mediterranean beaches and vibrant nightlife.",
    imageUrl: "https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800",
    latitude: 41.3851,
    longitude: 2.1734,
    timezone: "Europe/Madrid",
    currency: "EUR",
    language: "Spanish",
    popularity: 91,
    costIndex: 110,
    _count: { activities: 4 },
  },
  {
    id: "city-dubai",
    name: "Dubai",
    country: "UAE",
    state: null,
    description: "Futuristic city of skyscrapers, luxury shopping, and desert adventures.",
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800",
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: "Asia/Dubai",
    currency: "AED",
    language: "Arabic",
    popularity: 89,
    costIndex: 140,
    _count: { activities: 3 },
  },
  {
    id: "city-bangkok",
    name: "Bangkok",
    country: "Thailand",
    state: null,
    description: "Vibrant capital with ornate temples, bustling markets, and legendary street food.",
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800",
    latitude: 13.7563,
    longitude: 100.5018,
    timezone: "Asia/Bangkok",
    currency: "THB",
    language: "Thai",
    popularity: 87,
    costIndex: 50,
    _count: { activities: 3 },
  },
  {
    id: "city-sydney",
    name: "Sydney",
    country: "Australia",
    state: null,
    description: "Iconic harbor city with stunning beaches, world-famous opera house, and outdoor lifestyle.",
    imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800",
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: "Australia/Sydney",
    currency: "AUD",
    language: "English",
    popularity: 86,
    costIndex: 140,
    _count: { activities: 3 },
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: "act-1",
    cityId: "city-paris",
    name: "Eiffel Tower Visit",
    description: "Skip-the-line access to the second floor and summit of the iconic Eiffel Tower",
    type: "SIGHTSEEING",
    duration: 120,
    cost: 26,
    currency: "EUR",
    rating: 4.7,
    popularity: 100,
    imageUrl: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=600",
    location: "Champ de Mars, 5 Av. Anatole France, 75007 Paris",
    city: MOCK_CITIES[0],
  },
  {
    id: "act-2",
    cityId: "city-paris",
    name: "Louvre Museum Tour",
    description: "Guided tour through the world's largest art museum including the Mona Lisa",
    type: "CULTURE",
    duration: 180,
    cost: 22,
    currency: "EUR",
    rating: 4.6,
    popularity: 95,
    imageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600",
    location: "Rue de Rivoli, 75001 Paris",
    city: MOCK_CITIES[0],
  },
  {
    id: "act-3",
    cityId: "city-tokyo",
    name: "Shibuya Crossing Experience",
    description: "Experience the world's busiest pedestrian crossing and explore Shibuya",
    type: "SIGHTSEEING",
    duration: 90,
    cost: 0,
    currency: "JPY",
    rating: 4.5,
    popularity: 100,
    imageUrl: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=600",
    location: "Shibuya Station, Tokyo",
    city: MOCK_CITIES[1],
  },
  {
    id: "act-4",
    cityId: "city-nyc",
    name: "Statue of Liberty & Ellis Island",
    description: "Ferry to the Statue of Liberty including pedestal access and Ellis Island museum",
    type: "SIGHTSEEING",
    duration: 240,
    cost: 24,
    currency: "USD",
    rating: 4.6,
    popularity: 96,
    imageUrl: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?w=600",
    location: "Battery Park, New York",
    city: MOCK_CITIES[2],
  },
  {
    id: "act-5",
    cityId: "city-rome",
    name: "Colosseum & Roman Forum Tour",
    description: "Skip-the-line access to the ancient amphitheater and gladiators' arena",
    type: "CULTURE",
    duration: 180,
    cost: 28,
    currency: "EUR",
    rating: 4.8,
    popularity: 98,
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600",
    location: "Piazza del Colosseo, 1, 00184 Roma",
    city: MOCK_CITIES[3],
  },
];

export const MOCK_TRIPS = [
  {
    id: "trip-euro-summer",
    userId: "demo-user-id",
    title: "European Grand Tour",
    description: "2-week summer adventure through Paris, Rome, and Barcelona.",
    status: "PLANNING",
    startDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 3500,
    currency: "USD",
    coverImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    isPublic: true,
    shareToken: "euro-tour-2026",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stops: [
      {
        id: "stop-1",
        tripId: "trip-euro-summer",
        cityId: "city-paris",
        orderIndex: 0,
        arrivalDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        departureDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Stay near the Seine",
        city: MOCK_CITIES[0],
        activities: [],
      },
      {
        id: "stop-2",
        tripId: "trip-euro-summer",
        cityId: "city-rome",
        orderIndex: 1,
        arrivalDate: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000).toISOString(),
        departureDate: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Explore historical sites",
        city: MOCK_CITIES[3],
        activities: [],
      },
      {
        id: "stop-3",
        tripId: "trip-euro-summer",
        cityId: "city-barcelona",
        orderIndex: 2,
        arrivalDate: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000).toISOString(),
        departureDate: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Beach and tapas",
        city: MOCK_CITIES[6],
        activities: [],
      },
    ],
    expenses: [
      {
        id: "exp-1",
        tripId: "trip-euro-summer",
        userId: "demo-user-id",
        title: "Flights (NYC -> CDG)",
        amount: 850,
        currency: "USD",
        category: "TRANSPORT",
        date: new Date().toISOString(),
      },
      {
        id: "exp-2",
        tripId: "trip-euro-summer",
        userId: "demo-user-id",
        title: "Paris Boutique Hotel",
        amount: 600,
        currency: "EUR",
        category: "ACCOMMODATION",
        date: new Date().toISOString(),
      },
    ],
    _count: { stops: 3, expenses: 2 },
  },
  {
    id: "trip-tokyo-adventure",
    userId: "demo-user-id",
    title: "Tokyo & Kyoto Discovery",
    description: "Temples, culinary adventures, and futuristic skyline.",
    status: "CONFIRMED",
    startDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
    endDate: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000).toISOString(),
    budget: 4200,
    currency: "USD",
    coverImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    isPublic: true,
    shareToken: "tokyo-exp-2026",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stops: [
      {
        id: "stop-tokyo-1",
        tripId: "trip-tokyo-adventure",
        cityId: "city-tokyo",
        orderIndex: 0,
        arrivalDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        departureDate: new Date(Date.now() + 55 * 24 * 60 * 60 * 1000).toISOString(),
        notes: "Shinjuku stay",
        city: MOCK_CITIES[1],
        activities: [],
      },
    ],
    expenses: [],
    _count: { stops: 1, expenses: 0 },
  },
];

export const MOCK_COMMUNITY_POSTS = [
  {
    id: "post-1",
    userId: "user-1",
    title: "Hidden Gems in Paris: 5 Cafés You Shouldn't Miss",
    content: "When traveling to Paris, avoid the tourist traps near the Eiffel Tower. Head over to the Canal Saint-Martin and Le Marais for unbelievable coffee and croissants!",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800",
    likesCount: 24,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    user: {
      id: "user-1",
      name: "Sophia Laurent",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150",
    },
    city: MOCK_CITIES[0],
    comments: [
      {
        id: "c-1",
        content: "Bookmarking this for my upcoming trip in May! Thanks!",
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        user: { name: "Alex Chen", image: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150" },
      },
    ],
    likes: [],
  },
  {
    id: "post-2",
    userId: "user-2",
    title: "Ultimate 7-Day Tokyo Itinerary",
    content: "From teamLab Borderless to the back alleys of Omoide Yokocho, here is my complete breakdown of an unforgettable week in Tokyo.",
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    likesCount: 42,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    user: {
      id: "user-2",
      name: "Kenji Sato",
      image: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150",
    },
    city: MOCK_CITIES[1],
    comments: [],
    likes: [],
  },
];
